export const FOOD_LIST_REQUEST = "FOOD_LIST_REQUEST";
export const FOOD_LIST_SUCCESS = "FOOD_LIST_SUCCESS";
export const FOOD_LIST_FAIL = "FOOD_LIST_FAIL";

export const FOOD_DETAILS_REQUEST = "FOOD_DETAILS_REQUEST";
export const FOOD_DETAILS_SUCCESS = "FOOD_DETAILS_SUCCESS";
export const FOOD_DETAILS_FAIL = "FOOD_DETAILS_FAIL";

export const FOOD_DELETE_REQUEST = "FOOD_DELETE_REQUEST";
export const FOOD_DELETE_SUCCESS = "FOOD_DELETE_SUCCESS";
export const FOOD_DELETE_FAIL = "FOOD_DELETE_FAIL";

export const FOOD_CREATE_REQUEST = "FOOD_CREATE_REQUEST";
export const FOOD_CREATE_SUCCESS = "FOOD_CREATE_SUCCESS";
export const FOOD_CREATE_FAIL = "FOOD_CREATE_FAIL";
export const FOOD_CREATE_RESET = "FOOD_CREATE_RESET";
