export const SPECIALTY_LIST_REQUEST = "SPECIALTY_LIST_REQUEST";
export const SPECIALTY_LIST_SUCCESS = "SPECIALTY_LIST_SUCCESS";
export const SPECIALTY_LIST_FAIL = "SPECIALTY_LIST_FAIL";

export const SPECIALTY_DETAILS_REQUEST = "SPECIALTY_DETAILS_REQUEST";
export const SPECIALTY_DETAILS_SUCCESS = "SPECIALTY_DETAILS_SUCCESS";
export const SPECIALTY_DETAILS_FAIL = "SPECIALTY_DETAILS_FAIL";

export const SPECIALTY_DELETE_REQUEST = "SPECIALTY_DELETE_REQUEST";
export const SPECIALTY_DELETE_SUCCESS = "SPECIALTY_DELETE_SUCCESS";
export const SPECIALTY_DELETE_FAIL = "SPECIALTY_DELETE_FAIL";

export const SPECIALTY_CREATE_REQUEST = "SPECIALTY_CREATE_REQUEST";
export const SPECIALTY_CREATE_SUCCESS = "SPECIALTY_CREATE_SUCCESS";
export const SPECIALTY_CREATE_FAIL = "SPECIALTY_CREATE_FAIL";
export const SPECIALTY_CREATE_RESET = "SPECIALTY_CREATE_RESET";

export const SPECIALTY_UPDATE_REQUEST = "SPECIALTY_UPDATE_REQUEST";
export const SPECIALTY_UPDATE_SUCCESS = "SPECIALTY_UPDATE_SUCCESS";
export const SPECIALTY_UPDATE_FAIL = "SPECIALTY_UPDATE_FAIL";
export const SPECIALTY_UPDATE_RESET = "SPECIALTY_UPDATE_RESET";
