export const SPECIALTY_LIST_REQUEST = "SPECIALTY_LIST_REQUEST";
export const SPECIALTY_LIST_SUCCESS = "SPECIALTY_LIST_SUCCESS";
export const SPECIALTY_LIST_FAIL = "SPECIALTY_LIST_FAIL";

export const SPECIALTY_DETAILS_REQUEST = "SPECIALTY_DETAILS_REQUEST";
export const SPECIALTY_DETAILS_SUCCESS = "SPECIALTY_DETAILS_SUCCESS";
export const SPECIALTY_DETAILS_FAIL = "SPECIALTY_DETAILS_FAIL";
