export const TRAVEL_LIST_REQUEST = "TRAVEL_LIST_REQUEST";
export const TRAVEL_LIST_SUCCESS = "TRAVEL_LIST_SUCCESS";
export const TRAVEL_LIST_FAIL = "TRAVEL_LIST_FAIL";

export const TRAVEL_DETAILS_REQUEST = "TRAVEL_DETAILS_REQUEST";
export const TRAVEL_DETAILS_SUCCESS = "TRAVEL_DETAILS_SUCCESS";
export const TRAVEL_DETAILS_FAIL = "TRAVEL_DETAILS_FAIL";

export const TRAVEL_DELETE_REQUEST = "TRAVEL_DELETE_REQUEST";
export const TRAVEL_DELETE_SUCCESS = "TRAVEL_DELETE_SUCCESS";
export const TRAVEL_DELETE_FAIL = "TRAVEL_DELETE_FAIL";

export const TRAVEL_CREATE_REQUEST = "TRAVEL_CREATE_REQUEST";
export const TRAVEL_CREATE_SUCCESS = "TRAVEL_CREATE_SUCCESS";
export const TRAVEL_CREATE_FAIL = "TRAVEL_CREATE_FAIL";
export const TRAVEL_CREATE_RESET = "TRAVEL_CREATE_RESET";

export const TRAVEL_UPDATE_REQUEST = "TRAVEL_UPDATE_REQUEST";
export const TRAVEL_UPDATE_SUCCESS = "TRAVEL_UPDATE_SUCCESS";
export const TRAVEL_UPDATE_FAIL = "TRAVEL_UPDATE_FAIL";
export const TRAVEL_UPDATE_RESET = "TRAVEL_UPDATE_RESET";

export const TRAVEL_CREATE_REVIEW_REQUEST = "TRAVEL_CREATE_REVIEW_REQUEST";
export const TRAVEL_CREATE_REVIEW_SUCCESS = "TRAVEL_CREATE_REVIEW_SUCCESS";
export const TRAVEL_CREATE_REVIEW_FAIL = "TRAVEL_CREATE_REVIEW_FAIL";
export const TRAVEL_CREATE_REVIEW_RESET = "TRAVEL_CREATE_REVIEW_RESET";
