export const TRAVEL_LIST_REQUEST = "TRAVEL_LIST_REQUEST";
export const TRAVEL_LIST_SUCCESS = "TRAVEL_LIST_SUCCESS";
export const TRAVEL_LIST_FAIL = "TRAVEL_LIST_FAIL";

export const TRAVEL_DETAILS_REQUEST = "TRAVEL_DETAILS_REQUEST";
export const TRAVEL_DETAILS_SUCCESS = "TRAVEL_DETAILS_SUCCESS";
export const TRAVEL_DETAILS_FAIL = "TRAVEL_DETAILS_FAIL";

export const TRAVEL_DELETE_REQUEST = "TRAVEL_DELETE_REQUEST";
export const TRAVEL_DELETE_SUCCESS = "TRAVEL_DELETE_SUCCESS";
export const TRAVEL_DELETE_FAIL = "TRAVEL_DELETE_FAIL";
