export const VILLA_LIST_REQUEST = "VILLA_LIST_REQUEST";
export const VILLA_LIST_SUCCESS = "VILLA_LIST_SUCCESS";
export const VILLA_LIST_FAIL = "VILLA_LIST_FAIL";

export const VILLA_DETAILS_REQUEST = "VILLA_DETAILS_REQUEST";
export const VILLA_DETAILS_SUCCESS = "VILLA_DETAILS_SUCCESS";
export const VILLA_DETAILS_FAIL = "VILLA_DETAILS_FAIL";

export const VILLA_DELETE_REQUEST = "VILLA_DELETE_REQUEST";
export const VILLA_DELETE_SUCCESS = "VILLA_DELETE_SUCCESS";
export const VILLA_DELETE_FAIL = "VILLA_DELETE_FAIL";
