export const VILLA_LIST_REQUEST = "VILLA_LIST_REQUEST";
export const VILLA_LIST_SUCCESS = "VILLA_LIST_SUCCESS";
export const VILLA_LIST_FAIL = "VILLA_LIST_FAIL";

export const VILLA_DETAILS_REQUEST = "VILLA_DETAILS_REQUEST";
export const VILLA_DETAILS_SUCCESS = "VILLA_DETAILS_SUCCESS";
export const VILLA_DETAILS_FAIL = "VILLA_DETAILS_FAIL";

export const VILLA_DELETE_REQUEST = "VILLA_DELETE_REQUEST";
export const VILLA_DELETE_SUCCESS = "VILLA_DELETE_SUCCESS";
export const VILLA_DELETE_FAIL = "VILLA_DELETE_FAIL";

export const VILLA_CREATE_REQUEST = "VILLA_CREATE_REQUEST";
export const VILLA_CREATE_SUCCESS = "VILLA_CREATE_SUCCESS";
export const VILLA_CREATE_FAIL = "VILLA_CREATE_FAIL";
export const VILLA_CREATE_RESET = "VILLA_CREATE_RESET";

export const VILLA_UPDATE_REQUEST = "VILLA_UPDATE_REQUEST";
export const VILLA_UPDATE_SUCCESS = "VILLA_UPDATE_SUCCESS";
export const VILLA_UPDATE_FAIL = "VILLA_UPDATE_FAIL";
export const VILLA_UPDATE_RESET = "VILLA_UPDATE_RESET";

export const VILLA_CREATE_REVIEW_REQUEST = "VILLA_CREATE_REVIEW_REQUEST";
export const VILLA_CREATE_REVIEW_SUCCESS = "VILLA_CREATE_REVIEW_SUCCESS";
export const VILLA_CREATE_REVIEW_FAIL = "VILLA_CREATE_REVIEW_FAIL";
export const VILLA_CREATE_REVIEW_RESET = "VILLA_CREATE_REVIEW_RESET";
